framework:
    messenger:
        failure_transport: failed

        transports:
            default:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: telegram_app_exchange
                        type: direct
                    queues:
                        default:
                            arguments:
                                x-dead-letter-exchange: failed_exchange
                                x-dead-letter-routing-key: failed
                retry_strategy:
                    max_retries: 3
                    delay: 10000
                    multiplier: 2

            failed:
                dsn: '%env(MESSENGER_FAILED_DSN)%'
                options:
                    exchange:
                        name: failed_exchange
                        type: direct
                    queues:
                        failed_queue:
                            binding_keys: [ failed ]

        routing:
            'App\Message\ManageEventStatusMessage': default

