### /adminRefferal
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431014,
    "message": {
        "message_id": 657,
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "date": 1765660185,
        "text": "\ud83d\udc65 \u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044b"
    }
}

### show_top_referral
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431011,
    "callback_query": {
        "id": "1295669257702798314",
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "message": {
            "message_id": 648,
            "from": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "chat": {
                "id": 301671507,
                "first_name": "Panna",
                "last_name": "Caliano",
                "username": "PannaPro",
                "type": "private"
            },
            "date": 1765658696,
            "text": "\u0427\u0438\u0441\u043b\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432 \u0432 \u0431\u043e\u0442\u0435: 2\n\n\u041e\u0431\u0449\u0430\u044f \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u043f\u043e \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u0430\u043c\n\u0412\u0441\u0435\u0433\u043e: 1\n\u0421\u0435\u0433\u043e\u0434\u043d\u044f: 0\n\u0417\u0430 \u043d\u0435\u0434\u0435\u043b\u044e: 1\n\n\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u0430\u043c:",
            "entities": [
                {
                    "offset": 0,
                    "length": 24,
                    "type": "bold"
                },
                {
                    "offset": 28,
                    "length": 29,
                    "type": "bold"
                }
            ],
            "reply_markup": {
                "inline_keyboard": [
                    [
                        {
                            "text": "\ud83c\udfc6 \u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0442\u043e\u043f\u043e\u0432",
                            "callback_data": "show_top_referral"
                        }
                    ]
                ]
            }
        },
        "chat_instance": "5208739627955975931",
        "data": "show_top_referral"
    }
}

### participant_referral
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431013,
    "callback_query": {
        "id": "1295669258969256663",
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "message": {
            "message_id": 652,
            "from": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "chat": {
                "id": 301671507,
                "first_name": "Panna",
                "last_name": "Caliano",
                "username": "PannaPro",
                "type": "private"
            },
            "date": 1765658988,
            "text": "\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u0430\u043c:",
            "reply_markup": {
                "inline_keyboard": [
                    [
                        {
                            "text": "\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044b",
                            "callback_data": "participantReferral"
                        },
                        {
                            "text": "\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044b +\u0426\u0414",
                            "callback_data": "targetActionReferral"
                        }
                    ]
                ]
            }
        },
        "chat_instance": "5208739627955975931",
        "data": "participant_referral"
    }
}

### back_to_admin_menu
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431016,
    "callback_query": {
        "id": "1295669257616013041",
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "ru"
        },
        "message": {
            "message_id": 663,
            "from": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "chat": {
                "id": 301671507,
                "first_name": "Panna",
                "last_name": "Caliano",
                "username": "PannaPro",
                "type": "private"
            },
            "date": 1765663311,
            "text": "\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430\u043c (\u0441\u0442\u0430\u0442\u0443\u0441 participant)\n\n\u0412\u044b\u0431\u0435\u0440\u0438 \u0434\u0430\u0442\u0443 \u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430.\n\n\u0414\u043b\u044f \u0430\u043b\u044c\u0442\u0435\u0440\u043d\u0430\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u043f\u043e\u0438\u0441\u043a\u0430 \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043a\u043e\u043c\u0430\u043d\u0434\u0443 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435:\n\u0414\u0435\u043d\u044c 01-12-2025\n\u0414\u0430\u0442\u044b 01-12-2025 31-12-2025",
            "entities": [
                {
                    "offset": 0,
                    "length": 40,
                    "type": "bold"
                },
                {
                    "offset": 121,
                    "length": 15,
                    "type": "bold"
                },
                {
                    "offset": 137,
                    "length": 26,
                    "type": "bold"
                }
            ],
            "reply_markup": {
                "inline_keyboard": [
                    [
                        {
                            "text": "\u0417\u0430 \u0432\u0441\u0435 \u0432\u0440\u0435\u043c\u044f",
                            "callback_data": "allPeriod"
                        },
                        {
                            "text": "\u0421\u0435\u0433\u043e\u0434\u043d\u044f",
                            "callback_data": "dayPeriod"
                        },
                        {
                            "text": "\u0417\u0430 \u043d\u0435\u0434\u0435\u043b\u044e",
                            "callback_data": "weekPeriod"
                        }
                    ],
                    [
                        {
                            "text": "\u041d\u0430\u0437\u0430\u0434",
                            "callback_data": "back_to_referral_menu"
                        },
                        {
                            "text": "\u0413\u043b\u0430\u0432\u043d\u043e\u0435 \u043c\u0435\u043d\u044e",
                            "callback_data": "back_to_admin_menu"
                        }
                    ]
                ]
            }
        },
        "chat_instance": "5208739627955975931",
        "data": "back_to_admin_menu"
    }
}

### back_to_referal_menu
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431017,
    "callback_query": {
        "id": "1295669259347634410",
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "ru"
        },
        "message": {
            "message_id": 667,
            "from": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "chat": {
                "id": 301671507,
                "first_name": "Panna",
                "last_name": "Caliano",
                "username": "PannaPro",
                "type": "private"
            },
            "date": 1765663420,
            "text": "\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430\u043c (\u0441\u0442\u0430\u0442\u0443\u0441 participant)\n\n\u0412\u044b\u0431\u0435\u0440\u0438 \u0434\u0430\u0442\u0443 \u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430.\n\n\u0414\u043b\u044f \u0430\u043b\u044c\u0442\u0435\u0440\u043d\u0430\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u043f\u043e\u0438\u0441\u043a\u0430 \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043a\u043e\u043c\u0430\u043d\u0434\u0443 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435:\n\u0414\u0435\u043d\u044c 01-12-2025\n\u0414\u0430\u0442\u044b 01-12-2025 31-12-2025",
            "entities": [
                {
                    "offset": 0,
                    "length": 40,
                    "type": "bold"
                },
                {
                    "offset": 121,
                    "length": 15,
                    "type": "bold"
                },
                {
                    "offset": 137,
                    "length": 26,
                    "type": "bold"
                }
            ],
            "reply_markup": {
                "inline_keyboard": [
                    [
                        {
                            "text": "\u0417\u0430 \u0432\u0441\u0435 \u0432\u0440\u0435\u043c\u044f",
                            "callback_data": "allPeriod"
                        },
                        {
                            "text": "\u0421\u0435\u0433\u043e\u0434\u043d\u044f",
                            "callback_data": "dayPeriod"
                        },
                        {
                            "text": "\u0417\u0430 \u043d\u0435\u0434\u0435\u043b\u044e",
                            "callback_data": "weekPeriod"
                        }
                    ],
                    [
                        {
                            "text": "\u041d\u0430\u0437\u0430\u0434",
                            "callback_data": "back_to_referral_menu"
                        },
                        {
                            "text": "\u0413\u043b\u0430\u0432\u043d\u043e\u0435 \u043c\u0435\u043d\u044e",
                            "callback_data": "back_to_admin_menu"
                        }
                    ]
                ]
            }
        },
        "chat_instance": "5208739627955975931",
        "data": "back_to_referral_menu"
    }
}

### all_period
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431019,
    "callback_query": {
        "id": "1295669256778001076",
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "ru"
        },
        "message": {
            "message_id": 678,
            "from": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "chat": {
                "id": 301671507,
                "first_name": "Panna",
                "last_name": "Caliano",
                "username": "PannaPro",
                "type": "private"
            },
            "date": 1765663664,
            "text": "\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430\u043c (\u0441\u0442\u0430\u0442\u0443\u0441 participant)\n\n\u0412\u044b\u0431\u0435\u0440\u0438 \u0434\u0430\u0442\u0443 \u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430.\n\n\u0414\u043b\u044f \u0430\u043b\u044c\u0442\u0435\u0440\u043d\u0430\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u043f\u043e\u0438\u0441\u043a\u0430 \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043a\u043e\u043c\u0430\u043d\u0434\u0443 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435:\n\u0414\u0435\u043d\u044c 01-12-2025\n\u0414\u0430\u0442\u044b 01-12-2025 31-12-2025",
            "entities": [
                {
                    "offset": 0,
                    "length": 40,
                    "type": "bold"
                },
                {
                    "offset": 121,
                    "length": 15,
                    "type": "bold"
                },
                {
                    "offset": 137,
                    "length": 26,
                    "type": "bold"
                }
            ],
            "reply_markup": {
                "inline_keyboard": [
                    [
                        {
                            "text": "\u0417\u0430 \u0432\u0441\u0435 \u0432\u0440\u0435\u043c\u044f",
                            "callback_data": "all_period"
                        },
                        {
                            "text": "\u0421\u0435\u0433\u043e\u0434\u043d\u044f",
                            "callback_data": "day_period"
                        },
                        {
                            "text": "\u0417\u0430 \u043d\u0435\u0434\u0435\u043b\u044e",
                            "callback_data": "week_period"
                        }
                    ],
                    [
                        {
                            "text": "\u041d\u0430\u0437\u0430\u0434",
                            "callback_data": "back_to_referral_menu"
                        },
                        {
                            "text": "\u0413\u043b\u0430\u0432\u043d\u043e\u0435 \u043c\u0435\u043d\u044e",
                            "callback_data": "back_to_admin_menu"
                        }
                    ]
                ]
            }
        },
        "chat_instance": "5208739627955975931",
        "data": "current_day_period"
    }
}

### back_to_chose_date
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431020,
    "callback_query": {
        "id": "1295669260688958699",
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "ru"
        },
        "message": {
            "message_id": 684,
            "from": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "chat": {
                "id": 301671507,
                "first_name": "Panna",
                "last_name": "Caliano",
                "username": "PannaPro",
                "type": "private"
            },
            "date": 1765664706,
            "text": "\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430\u043c (\u0441\u0442\u0430\u0442\u0443\u0441 participant) \u0437\u0430 \u0432\u0441\u0435 \u0432\u0440\u0435\u043c\u044f\n\n\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043a\u043e\u043b-\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432 \u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430:",
            "entities": [
                {
                    "offset": 0,
                    "length": 53,
                    "type": "bold"
                }
            ],
            "reply_markup": {
                "inline_keyboard": [
                    [
                        {
                            "text": "\u041d\u0430\u0437\u0430\u0434",
                            "callback_data": "back_to_chose_search_date"
                        }
                    ]
                ]
            }
        },
        "chat_instance": "5208739627955975931",
        "data": "back_to_chose_search_date"
    }
}

### count_of_referral
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431021,
    "message": {
        "message_id": 718,
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "ru"
        },
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "date": 1765665712,
        "text": "2412"
    }
}

### costum_day_period
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431032,
    "message": {
        "message_id": 721,
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "date": 1765720750,
        "text": "14-12-2025"
    }
}

### count_participant
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431033,
    "message": {
        "message_id": 725,
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "date": 1765721127,
        "text": "5"
    }
}

### count_participant
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66431050,
    "message": {
        "message_id": 16,
        "from": {
            "id": 374069994,
            "is_bot": false,
            "first_name": "\u1d18\u1d00\u1d0b\u1d07\u1d1b\u1d00",
            "username": "PAKETABKOCMOC",
            "language_code": "ru",
            "is_premium": true
        },
        "chat": {
            "id": -1003348099183,
            "title": "\u0422\u0435\u0441\u0442 \u0431\u043e\u0442\u0430",
            "type": "supergroup"
        },
        "date": 1765802396,
        "voice": {
            "duration": 9,
            "mime_type": "audio/ogg",
            "file_id": "AwACAgIAAyEFAATHj_BvAAMQaUABnJu7O1njg7hg1WoStok5bqQAAumDAAJHKgFKlvymBuDisFE2BA",
            "file_unique_id": "AgAD6YMAAkcqAUo",
            "file_size": 201928
        }
    }
}
