POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66430880,
    "message": {
        "message_id": 175,
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "date": 1765034048,
        "text": "\u0412\u0435\u0440\u043d\u0443\u0442\u044c\u0441\u044f \u0432 \u043c\u0435\u043d\u044e"
    }
}
