POST http://127.0.0.1/telegram/test-webhook
Content-Type: application/json

{
    "update_id": 66430851,
    "callback_query": {
        "id": "1295669260334175733",
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro"
        },
        "message": {
            "message_id": 12,
            "from": {"id": 6978124079, "is_bot": true, "first_name": "PAKETA_bot", "username": "Panpubgbot"},
            "chat": {"id": 301671507, "first_name": "Panna", "last_name": "Caliano", "username": "PannaPro", "type": "private"},
            "text": "Привет! Вот твоя кнопка:"
        },
        "chat_instance": "5208739627955975931",
        "data": "press_me"
    }
}
