### subscribe
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66430992,
    "callback_query": {
        "id": "1295669260024233592",
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "message": {
            "message_id": 545,
            "from": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "chat": {
                "id": 301671507,
                "first_name": "Panna",
                "last_name": "Caliano",
                "username": "PannaPro",
                "type": "private"
            },
            "date": 1765640777,
            "text": "\ud83d\udc4b \u041f\u0440\u0438\u0432\u0435\u0442, \u0434\u043e\u0440\u043e\u0433\u043e\u0439 \u0434\u0440\u0443\u0433!\n\n\u0427\u0442\u043e\u0431\u044b \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c\u0441\u044f \u0438\u0433\u0440\u043e\u0432\u044b\u043c \u0431\u043e\u0442\u043e\u043c \u043d\u0443\u0436\u043d\u0430 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u043d\u0430 \u043d\u0430\u0448 \u043a\u0430\u043d\u0430\u043b",
            "entities": [
                {
                    "offset": 3,
                    "length": 21,
                    "type": "bold"
                },
                {
                    "offset": 81,
                    "length": 5,
                    "type": "text_link",
                    "url": "https://t.me/PAKETAGAME?start=1"
                }
            ],
            "link_preview_options": {
                "url": "https://t.me/PAKETAGAME?start=1"
            },
            "reply_markup": {
                "inline_keyboard": [
                    [
                        {
                            "text": "\u041f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",
                            "callback_data": "subscription"
                        }
                    ]
                ]
            }
        },
        "chat_instance": "5208739627955975931",
        "data": "subscription"
    }
}


### subscribe
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66430886,
    "removed_chat_boost": {
        "chat": {
            "id": -1002900822842,
            "title": "\u1d3e\u1d2c\u1d37\u1d31\u1d40\u1d2c\u1d33\u1d2c\u1d39\u1d31\ud83d\ude80",
            "username": "PAKETAGAME",
            "type": "channel"
        },
        "boost_id": "61d4259469ce889266d479bec9b78129",
        "remove_date": 1765039622,
        "source": {
            "source": "premium",
            "user": {
                "id": 5107384094,
                "is_bot": false,
                "first_name": "Li\u2022",
                "username": "liooofe"
            }
        }
    }
}
