### my_chat_member (member)
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66430957,
    "my_chat_member": {
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "date": 1765392527,
        "old_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "kicked",
            "until_date": 0
        },
        "new_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "member"
        }
    }
}

### my_chat_member (kicked)
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66430956,
    "my_chat_member": {
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "date": 1765391152,
        "old_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "member"
        },
        "new_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "kicked",
            "until_date": 0
        }
    }
}
