
### subscribe
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66430928,
    "my_chat_member": {
        "chat": {
            "id": 829052422,
            "first_name": "\u0410\u043d\u044f \ud83e\uddf8",
            "username": "ann_ushka_t",
            "type": "private"
        },
        "from": {
            "id": 829052422,
            "is_bot": false,
            "first_name": "\u0410\u043d\u044f \ud83e\uddf8",
            "username": "ann_ushka_t",
            "language_code": "ru"
        },
        "date": 1765201274,
        "old_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "kicked",
            "until_date": 0
        },
        "new_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "member"
        }
    }
}
