### subscribe
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66430869,
    "my_chat_member": {
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "language_code": "en"
        },
        "date": 1765027250,
        "old_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "kicked",
            "until_date": 0
        },
        "new_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "member"
        }
    }
}

### unsubscribe
POST http://127.0.0.1/test-webhook
Content-Type: application/json

{
    "update_id": 66430868,
    "my_chat_member": {
        "chat": {
            "id": 301671507,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro",
            "type": "private"
        },
        "from": {
            "id": 301671507,
            "is_bot": false,
            "first_name": "Panna",
            "last_name": "Caliano",
            "username": "PannaPro"
        },
        "date": 1765027244,
        "old_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "member"
        },
        "new_chat_member": {
            "user": {
                "id": 6978124079,
                "is_bot": true,
                "first_name": "PAKETA_bot",
                "username": "Panpubgbot"
            },
            "status": "kicked",
            "until_date": 0
        }
    }
}
