<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123181707 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE telegram_event_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chat_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, bot_is_admin BOOLEAN NOT NULL, can_invite BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE event ADD game_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA755102661 FOREIGN KEY (game_group_id) REFERENCES telegram_event_group (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3BAE0AA755102661 ON event (game_group_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE telegram_event_group');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA755102661');
        $this->addSql('DROP INDEX UNIQ_3BAE0AA755102661');
        $this->addSql('ALTER TABLE event DROP game_group_id');
    }
}
