# Подключение
bind 0.0.0.0

protected-mode yes

# Пользователи и права
aclfile /usr/local/etc/redis/users.acl

# Кол-во логических баз данных внутри 1 экземпляра редис
databases 1

# Макс. потребление памяти
maxmemory 2gb

# Политика освобождения памяти (эвикт)
# (Выбрасывает наименее недавно используемый среди ключей, у которых задано время жизни (TTL))
maxmemory-policy volatile-lru

# Включает AOF-журнал (Append Only File)
appendonly yes

# Записывает на диск накопленные операции раз в секунду
appendfsync everysec

# RDB-снимки (snapshotting)
save 900 1
save 300 10
save 60 10000

# Уровень лога
loglevel notice

# Записывает клиентские запросы медленнее чем 10000 мкс (10 мс)
slowlog-log-slower-than 10000

# Максимальная длина списка записей для медленных запросов
slowlog-max-len 128

# Комманды платформы/движка > 100 мс будут залогированы
latency-monitor-threshold 100

# Логирование эвикта (политики освобождения памяти)
notify-keyspace-events Eex

# Время бездействия клиента (0 = живёт сколько угодно)
timeout 0

# Проверка активных подключений раз в 300 сек.
tcp-keepalive 300

# Обычные клиенты: без лимитов
client-output-buffer-limit normal 0 0 0

# Реплики: до 256 МБ сразу, или >64 МБ в течение 60 секунд
client-output-buffer-limit replica 256mb 64mb 60

# Подписчики Pub/Sub: до 32 МБ сразу, или >8 МБ в течение 60 секунд
client-output-buffer-limit pubsub 32mb 8mb 60